# Generated by Django 5.0.1 on 2024-07-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.RenameField(
            model_name='errormessages',
            old_name='full_text',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='infomessages',
            old_name='full_text',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.city'),
        ),
    ]
