# Generated by Django 5.0.1 on 2024-07-22 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0002_city_rename_full_text_errormessages_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.branch')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.product')),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.volume')),
            ],
            options={
                'unique_together': {('product', 'branch', 'volume', 'color')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.ManyToManyField(related_name='product_stocks', through='Mixon_shop.ProductStock', to='Mixon_shop.branch'),
        ),
    ]
