# Generated by Django 5.0.1 on 2024-07-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0004_color_rgb_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='vendor_code',
            field=models.CharField(default=23, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='default_name', max_length=256),
            preserve_default=False,
        ),
    ]
