# Generated by Django 5.0.1 on 2025-02-04 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0012_mainpagebanner_mainpagesections_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='goods_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.branch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.shipmentmethod'),
        ),
    ]
