# Generated by Django 5.0.1 on 2025-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0014_category_remove_order_products_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='Mixon_shop.OrderProduct', to='Mixon_shop.product'),
        ),
    ]
