# Generated by Django 5.0.1 on 2025-04-08 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0016_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagesections',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.category'),
        ),
    ]
