# Generated by Django 5.0.1 on 2025-04-13 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0017_alter_mainpagesections_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g., "Standard office hours"', max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='branch',
            name='working_hours',
        ),
        migrations.AddField(
            model_name='branch',
            name='schedule_template',
            field=models.ForeignKey(blank=True, help_text='Optional template for standard schedule', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mixon_shop.scheduletemplate'),
        ),
        migrations.CreateModel(
            name='BranchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('is_closed', models.BooleanField(default=False)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='Mixon_shop.branch')),
            ],
            options={
                'verbose_name': 'Branch Schedule',
                'verbose_name_plural': 'Branch Schedules',
                'unique_together': {('branch', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='BranchScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='Mixon_shop.branch')),
            ],
            options={
                'verbose_name': 'Branch Schedule Exception',
                'verbose_name_plural': 'Branch Schedule Exceptions',
                'unique_together': {('branch', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('is_closed', models.BooleanField(default=False)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Mixon_shop.scheduletemplate')),
            ],
            options={
                'verbose_name': 'Schedule Template Item',
                'verbose_name_plural': 'Schedule Template Items',
                'unique_together': {('template', 'day_of_week')},
            },
        ),
    ]
