# Generated by Django 5.0.1 on 2025-04-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0018_scheduletemplate_remove_branch_working_hours_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchschedule',
            options={'ordering': ['day_of_week'], 'verbose_name': 'Branch Schedule', 'verbose_name_plural': 'Branch Schedules'},
        ),
        migrations.AlterModelOptions(
            name='scheduletemplateitem',
            options={'ordering': ['day_of_week'], 'verbose_name': 'Schedule Template Item', 'verbose_name_plural': 'Schedule Template Items'},
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone_numbers',
            field=models.ManyToManyField(blank=True, to='Mixon_shop.phonenumber'),
        ),
    ]
