# Generated by Django 5.0.1 on 2025-04-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0019_alter_branchschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchschedule',
            options={'ordering': ['order'], 'verbose_name': 'Branch Schedule', 'verbose_name_plural': 'Branch Schedules'},
        ),
        migrations.AlterModelOptions(
            name='scheduletemplateitem',
            options={'ordering': ['order'], 'verbose_name': 'Schedule Template Item', 'verbose_name_plural': 'Schedule Template Items'},
        ),
        migrations.AddField(
            model_name='branchschedule',
            name='order',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='scheduletemplateitem',
            name='order',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
