# Generated by Django 5.0.1 on 2025-08-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0021_alter_news_options_alter_newscategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category/images/'),
        ),
    ]
