# Generated by Django 5.0.1 on 2025-08-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0022_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='news_category/images/'),
        ),
    ]
