# Generated by Django 5.0.1 on 2025-08-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0023_newscategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=256, unique=True, verbose_name='URL-имя'),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_category/images/', verbose_name='Иконка категории'),
        ),
    ]
