# Generated by Django 5.0.1 on 2025-08-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0024_newscategory_slug_alter_newscategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='news_category/images/', verbose_name='Иконка категории'),
        ),
    ]
