# Generated by Django 5.0.1 on 2025-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0025_alter_newscategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscategory',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='URL-имя'),
        ),
    ]
