# Generated by Django 5.0.1 on 2025-08-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0027_alter_newscategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpagesections',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mainpagesections',
            name='is_used',
        ),
    ]
