# Generated by Django 5.0.1 on 2025-08-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0028_remove_mainpagesections_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomparison',
            name='list_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
