# Generated by Django 5.0.1 on 2025-08-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0029_productcomparison_list_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
        migrations.AddField(
            model_name='branch',
            name='address_base',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Основной адрес'),
        ),
        migrations.AddField(
            model_name='branch',
            name='address_detail',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Уточняющий адрес'),
        ),
        migrations.AddField(
            model_name='branch',
            name='address_short',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Сокращенный адрес'),
        ),
    ]
