# Generated by Django 5.0.1 on 2025-08-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0030_remove_branch_address_branch_address_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address_short',
            field=models.CharField(default=33, max_length=512, verbose_name='Сокращенный адрес'),
            preserve_default=False,
        ),
    ]
