# Generated by Django 5.0.1 on 2025-08-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0031_alter_branch_address_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.ManyToManyField(blank=True, to='Mixon_shop.emailaddress'),
        ),
    ]
