# Generated by Django 5.0.1 on 2025-08-25 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0032_emailaddress_branch_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailaddress',
            old_name='email',
            new_name='address',
        ),
    ]
