# Generated by Django 5.0.1 on 2025-08-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0033_rename_email_emailaddress_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='product_types', to='Mixon_shop.category'),
        ),
    ]
