# Generated by Django 5.0.1 on 2025-08-26 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mixon_shop', '0035_alter_mainpagebanner_image_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bindingsubstance',
            options={'verbose_name': 'Основа', 'verbose_name_plural': 'Основы'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Филиал', 'verbose_name_plural': 'Филиалы'},
        ),
        migrations.AlterModelOptions(
            name='branchschedule',
            options={'ordering': ['order'], 'verbose_name': 'Расписание филиала', 'verbose_name_plural': 'Расписание филиалов'},
        ),
        migrations.AlterModelOptions(
            name='branchscheduleexception',
            options={'verbose_name': 'Исключение в расписании филиала', 'verbose_name_plural': 'Исключения в расписании филиалов'},
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Товар в корзине', 'verbose_name_plural': 'Товары в корзине'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория товара', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'verbose_name': 'Адрес э-почты', 'verbose_name_plural': 'Адреса э-почты'},
        ),
        migrations.AlterModelOptions(
            name='errormessages',
            options={'verbose_name': 'Сообщение об ошибке', 'verbose_name_plural': 'Сообщения об ошибке'},
        ),
        migrations.AlterModelOptions(
            name='favoriteproduct',
            options={'verbose_name': 'Товар в избранном', 'verbose_name_plural': 'Товары в избранном'},
        ),
        migrations.AlterModelOptions(
            name='infomessages',
            options={'verbose_name': 'Информационное сообщение', 'verbose_name_plural': 'Информационные сообщения'},
        ),
        migrations.AlterModelOptions(
            name='mainpagebanner',
            options={'verbose_name': 'Баннер на главной странице', 'verbose_name_plural': 'Баннеры на главной странице'},
        ),
        migrations.AlterModelOptions(
            name='mainpagesections',
            options={'verbose_name': 'Категория товаров на главной странице', 'verbose_name_plural': 'Категории товаров на главной странице'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'Статус заказа', 'verbose_name_plural': 'Статусы заказов'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Метод оплаты', 'verbose_name_plural': 'Методы оплаты'},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'Номер телефона', 'verbose_name_plural': 'Номера телефонов'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productcomparison',
            options={'verbose_name': 'Список сравнения', 'verbose_name_plural': 'Списки сравнения'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Картинка товара', 'verbose_name_plural': 'Картинки товаров'},
        ),
        migrations.AlterModelOptions(
            name='productstock',
            options={'verbose_name': 'Наличие в магазинах', 'verbose_name_plural': 'Наличие в магазинах'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Тип товара', 'verbose_name_plural': 'Типы товаров'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterModelOptions(
            name='recommendedproducts',
            options={'verbose_name': 'Рекомендованный товар', 'verbose_name_plural': 'Рекомендованные товары'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Область', 'verbose_name_plural': 'Области'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='salesleaders',
            options={'verbose_name': 'Лидер продаж', 'verbose_name_plural': 'Лидеры продаж'},
        ),
        migrations.AlterModelOptions(
            name='scheduletemplate',
            options={'verbose_name': 'Раскладка расписания', 'verbose_name_plural': 'Раскладки расписаний'},
        ),
        migrations.AlterModelOptions(
            name='scheduletemplateitem',
            options={'ordering': ['order'], 'verbose_name': 'Раскладка расписания', 'verbose_name_plural': 'Раскладки расписаний'},
        ),
        migrations.AlterModelOptions(
            name='shipmentmethod',
            options={'verbose_name': 'Метод доставки', 'verbose_name_plural': 'Методы доставки'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterModelOptions(
            name='volume',
            options={'verbose_name': 'Объём', 'verbose_name_plural': 'Объёмы'},
        ),
        migrations.AlterField(
            model_name='bindingsubstance',
            name='name',
            field=models.CharField(max_length=256, verbose_name='название основы'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.city', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.ManyToManyField(blank=True, to='Mixon_shop.emailaddress', verbose_name='адреса э-почты'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='map_info',
            field=models.TextField(verbose_name='информация о координатах карты'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone_numbers',
            field=models.ManyToManyField(blank=True, to='Mixon_shop.phonenumber', verbose_name='номера телефонов'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='schedule_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mixon_shop.scheduletemplate', verbose_name='Раскладка расписания'),
        ),
        migrations.AlterField(
            model_name='branchschedule',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='время закрытия'),
        ),
        migrations.AlterField(
            model_name='branchschedule',
            name='day_of_week',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, verbose_name='день недели'),
        ),
        migrations.AlterField(
            model_name='branchschedule',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='закрыто в этот день?'),
        ),
        migrations.AlterField(
            model_name='branchschedule',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='время открытия'),
        ),
        migrations.AlterField(
            model_name='branchscheduleexception',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='Mixon_shop.branch', verbose_name='филиал'),
        ),
        migrations.AlterField(
            model_name='branchscheduleexception',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='время закрытия'),
        ),
        migrations.AlterField(
            model_name='branchscheduleexception',
            name='date',
            field=models.DateField(verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='branchscheduleexception',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='закрыто в этот день?'),
        ),
        migrations.AlterField(
            model_name='branchscheduleexception',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='время открытия'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Mixon_shop.cart', verbose_name='корзина'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='кол-во'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category/images/', verbose_name='логотип категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='название категории'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=256, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, verbose_name='название цвета'),
        ),
        migrations.AlterField(
            model_name='color',
            name='rgb_code',
            field=models.CharField(max_length=50, verbose_name='цвет в формате RGB'),
        ),
        migrations.AlterField(
            model_name='color',
            name='vendor_code',
            field=models.CharField(max_length=50, verbose_name='артикул цвета'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='address',
            field=models.EmailField(max_length=254, unique=True, verbose_name='адрес э-почты'),
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='favoriteproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='mainpagebanner',
            name='description',
            field=models.TextField(verbose_name='описание банера'),
        ),
        migrations.AlterField(
            model_name='mainpagebanner',
            name='image',
            field=models.ImageField(upload_to='main_page/images/', verbose_name='изображение банера'),
        ),
        migrations.AlterField(
            model_name='mainpagebanner',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='должен ли сейчас отображаться'),
        ),
        migrations.AlterField(
            model_name='mainpagesections',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='goods_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='стоимость товаров'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=256, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.branch', verbose_name='филиал откуда заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.paymentmethod', verbose_name='метод оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='Mixon_shop.OrderProduct', to='Mixon_shop.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_code', to='Mixon_shop.promocode', verbose_name='промокод'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo_applied',
            field=models.BooleanField(default=False, verbose_name='применен ли промокод'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='стоимость доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.shipmentmethod', verbose_name='метод доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.orderstatus', verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='кол-во товара в заказе'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=256, verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='image',
            field=models.ImageField(upload_to='payment_methods/images/', verbose_name='логотип метода'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=256, verbose_name='метод оплаты'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=18, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='средняя оценка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='binding_substance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.bindingsubstance', verbose_name='вещество основы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.category', verbose_name='категория продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='consumption',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='потребление'),
        ),
        migrations.AlterField(
            model_name='product',
            name='density',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='плотность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dry_residue',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='сухой остаток'),
        ),
        migrations.AlterField(
            model_name='product',
            name='drying_time',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='время высыхания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_discounted',
            field=models.BooleanField(default=False, verbose_name='скидка активна?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_in_stock',
            field=models.BooleanField(default=False, verbose_name='есть в наличии?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='новинка?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, verbose_name='название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, to='Mixon_shop.product', verbose_name='покупают вместе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='similar_products',
            field=models.ManyToManyField(blank=True, to='Mixon_shop.product', verbose_name='похожие продукты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='solvent',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='расстворитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stocks',
            field=models.ManyToManyField(related_name='product_stocks', through='Mixon_shop.ProductStock', to='Mixon_shop.branch', verbose_name='наличие'),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='хранение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tool_cleaning',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='очистка инструмента'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.producttype', verbose_name='тип продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='назначение продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='working_tools',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='инструменты для работы'),
        ),
        migrations.AlterField(
            model_name='productcomparison',
            name='list_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='номер сравнения'),
        ),
        migrations.AlterField(
            model_name='productcomparison',
            name='products',
            field=models.ManyToManyField(to='Mixon_shop.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='productcomparison',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/images/', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Mixon_shop.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.branch', verbose_name='филиал'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.color', verbose_name='цвет'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='кол-во'),
        ),
        migrations.AlterField(
            model_name='productstock',
            name='volume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mixon_shop.volume', verbose_name='объём'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='product_types', to='Mixon_shop.category', verbose_name='к каким категориям относится'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=256, verbose_name='вид товара'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(blank=True, help_text='Оставьте пустым для генерации кода стандартизированного вида, например "Iua4CEqQj5B0Np7y"', max_length=50, null=True, unique=True, verbose_name='код скидки'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Процент'), ('amount', 'Число')], max_length=10, verbose_name='тип скидки'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='размер скидки'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата когда заканчивается действие'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='max_usage_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='максимальное кол-во использований'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='usage_count',
            field=models.PositiveIntegerField(default=0, verbose_name='кол-во использований'),
        ),
        migrations.AlterField(
            model_name='recommendedproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_products', to='Mixon_shop.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=256, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='review',
            name='cons',
            field=models.TextField(blank=True, null=True, verbose_name='минусы товара'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Mixon_shop.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pros',
            field=models.TextField(blank=True, null=True, verbose_name='плюсы товара'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(verbose_name='поставленная оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.TextField(blank=True, null=True, verbose_name='текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AlterField(
            model_name='salesleaders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_leaders', to='Mixon_shop.product', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='scheduletemplate',
            name='name',
            field=models.CharField(help_text='Раскладка расписания, например "Стандартное расписание Одесса"', max_length=256, verbose_name='название раскладки'),
        ),
        migrations.AlterField(
            model_name='scheduletemplateitem',
            name='close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='время закрытия'),
        ),
        migrations.AlterField(
            model_name='scheduletemplateitem',
            name='day_of_week',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, verbose_name='день недели'),
        ),
        migrations.AlterField(
            model_name='scheduletemplateitem',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='закрыто в этот день?'),
        ),
        migrations.AlterField(
            model_name='scheduletemplateitem',
            name='open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='время открытия'),
        ),
        migrations.AlterField(
            model_name='shipmentmethod',
            name='image',
            field=models.ImageField(upload_to='shipment_methods/images/', verbose_name='логотип метода'),
        ),
        migrations.AlterField(
            model_name='shipmentmethod',
            name='name',
            field=models.CharField(max_length=256, verbose_name='метод достаки'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=256, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='компания'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mixon_shop.region', verbose_name='область'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='регистрационный номер'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='объём'),
        ),
    ]
